server:
  port: 8003
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    hostname: replica2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:123456@replica1:8002/eureka/
