package com.remmy.registrymanager.repository.mapper;

import com.remmy.registrymanager.repository.model.ImageCache;
import com.remmy.registrymanager.repository.model.ImageCacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    long countByExample(ImageCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int deleteByExample(ImageCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int insert(ImageCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int insertSelective(ImageCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    List<ImageCache> selectByExample(ImageCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    ImageCache selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") ImageCache record, @Param("example") ImageCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByExample(@Param("record") ImageCache record, @Param("example") ImageCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByPrimaryKeySelective(ImageCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_cache
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByPrimaryKey(ImageCache record);
}