package com.remmy.registrymanager.repository.mapper;

import com.remmy.registrymanager.repository.model.RegistryDefine;
import com.remmy.registrymanager.repository.model.RegistryDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegistryDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    long countByExample(RegistryDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int deleteByExample(RegistryDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int insert(RegistryDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int insertSelective(RegistryDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    List<RegistryDefine> selectByExample(RegistryDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    RegistryDefine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") RegistryDefine record, @Param("example") RegistryDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByExample(@Param("record") RegistryDefine record, @Param("example") RegistryDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByPrimaryKeySelective(RegistryDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registry_define
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    int updateByPrimaryKey(RegistryDefine record);
}