spring:
  datasource:
    jdbc-url: jdbc:mysql://192.168.109.6:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        enable-lazy-load-no-trans: true
    open-in-view: true