server:
  port: 8101
spring:
  application:
    name: eureka-client1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@replica1:8002/eureka/,http://admin:123456@replica2:8003/eureka/
