package com.remmy.registrymanager.repository.model;

import java.util.Date;

public class ImageCache {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.id
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.image_id
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.name
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.tag
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.size
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.registry_address
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String registryAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.registry_name
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String registryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.config
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String config;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_cache.refresh_time
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Date refreshTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.id
     *
     * @return the value of image_cache.id
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.id
     *
     * @param id the value for image_cache.id
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.image_id
     *
     * @return the value of image_cache.image_id
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.image_id
     *
     * @param imageId the value for image_cache.image_id
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setImageId(String imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.name
     *
     * @return the value of image_cache.name
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.name
     *
     * @param name the value for image_cache.name
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.tag
     *
     * @return the value of image_cache.tag
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.tag
     *
     * @param tag the value for image_cache.tag
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.size
     *
     * @return the value of image_cache.size
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.size
     *
     * @param size the value for image_cache.size
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.registry_address
     *
     * @return the value of image_cache.registry_address
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getRegistryAddress() {
        return registryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.registry_address
     *
     * @param registryAddress the value for image_cache.registry_address
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setRegistryAddress(String registryAddress) {
        this.registryAddress = registryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.registry_name
     *
     * @return the value of image_cache.registry_name
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getRegistryName() {
        return registryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.registry_name
     *
     * @param registryName the value for image_cache.registry_name
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setRegistryName(String registryName) {
        this.registryName = registryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.config
     *
     * @return the value of image_cache.config
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.config
     *
     * @param config the value for image_cache.config
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_cache.refresh_time
     *
     * @return the value of image_cache.refresh_time
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Date getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_cache.refresh_time
     *
     * @param refreshTime the value for image_cache.refresh_time
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setRefreshTime(Date refreshTime) {
        this.refreshTime = refreshTime;
    }
}