package com.remmy.registrymanager.repository.model;

import com.remmy.registrymanager.utils.RegistryType;
import java.util.Date;

public class RegistryDefine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.ID
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.NAME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.HOST
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.PORT
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.USER
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.PASSWORD
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.HARBOR_PRODUCT_NAME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String harborProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.HARBOR_PRODUCT_ID
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Integer harborProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.TYPE
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private RegistryType type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.SCHEME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private String scheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.HEALTH
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Integer health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.CREATE_TIME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registry_define.UPDATE_TIME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.ID
     *
     * @return the value of registry_define.ID
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.ID
     *
     * @param id the value for registry_define.ID
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.NAME
     *
     * @return the value of registry_define.NAME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.NAME
     *
     * @param name the value for registry_define.NAME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.HOST
     *
     * @return the value of registry_define.HOST
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.HOST
     *
     * @param host the value for registry_define.HOST
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.PORT
     *
     * @return the value of registry_define.PORT
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.PORT
     *
     * @param port the value for registry_define.PORT
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.USER
     *
     * @return the value of registry_define.USER
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.USER
     *
     * @param user the value for registry_define.USER
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.PASSWORD
     *
     * @return the value of registry_define.PASSWORD
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.PASSWORD
     *
     * @param password the value for registry_define.PASSWORD
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.HARBOR_PRODUCT_NAME
     *
     * @return the value of registry_define.HARBOR_PRODUCT_NAME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getHarborProductName() {
        return harborProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.HARBOR_PRODUCT_NAME
     *
     * @param harborProductName the value for registry_define.HARBOR_PRODUCT_NAME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setHarborProductName(String harborProductName) {
        this.harborProductName = harborProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.HARBOR_PRODUCT_ID
     *
     * @return the value of registry_define.HARBOR_PRODUCT_ID
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Integer getHarborProductId() {
        return harborProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.HARBOR_PRODUCT_ID
     *
     * @param harborProductId the value for registry_define.HARBOR_PRODUCT_ID
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setHarborProductId(Integer harborProductId) {
        this.harborProductId = harborProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.TYPE
     *
     * @return the value of registry_define.TYPE
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public RegistryType getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.TYPE
     *
     * @param type the value for registry_define.TYPE
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setType(RegistryType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.SCHEME
     *
     * @return the value of registry_define.SCHEME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.SCHEME
     *
     * @param scheme the value for registry_define.SCHEME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.HEALTH
     *
     * @return the value of registry_define.HEALTH
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Integer getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.HEALTH
     *
     * @param health the value for registry_define.HEALTH
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setHealth(Integer health) {
        this.health = health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.CREATE_TIME
     *
     * @return the value of registry_define.CREATE_TIME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.CREATE_TIME
     *
     * @param createTime the value for registry_define.CREATE_TIME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registry_define.UPDATE_TIME
     *
     * @return the value of registry_define.UPDATE_TIME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registry_define.UPDATE_TIME
     *
     * @param updateTime the value for registry_define.UPDATE_TIME
     *
     * @mbg.generated Wed Dec 09 12:14:53 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}