server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@replica1:8002/eureka/,http://admin:123456@replica2:8003/eureka/
service-url:
  user-service: http://user-service
logging:
  level:
    com:
      netflix:
        loadbalancer: debug
