server:
  port: 8201
spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@replica1:8002/eureka/,http://admin:123456@replica2:8003/eureka/
